services:
  - docker

before_install:
  - docker pull synocommunity/spksrc

script:
  - docker run -it -v ${TRAVIS_BUILD_DIR}:/spksrc -w /spksrc synocommunity/spksrc bash -c 'make clean && make setup && make -C spk/python3 arch-armada370'